import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { Toaster } from "~/components/ui/sonner"
import { ThemeProvider } from "~/components/theme-provider"

import Footer from "~/components/Footer";

export const metadata: Metadata = {
	title: "EduBank.AI",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/logo.png" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
			<body className="min-h-screen flex flex-col">
				<ThemeProvider
          		  attribute="class"
          		  defaultTheme="dark"
          		  enableSystem
          		  disableTransitionOnChange
          		>
					<main className="flex flex-col justify-between p-5 min-h-screen bg-gradient-to-br from-slate-300 to-gray-100 dark:from-gray-950 dark:to-gray-800">
						{children}
						<Footer />
					</main>
					<Toaster richColors closeButton />
				</ThemeProvider>
			</body>
		</html>
	);
}
