"use client"

import Head from "next/head";
import Link from "next/link";

export default function Home() {
	return (
		<>
		<div className="min-h-screen flex items-center justify-center p-4 bg-primary text-white">
			<Head>
				<title>EduBank</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex min-h-screen flex-col items-center justify-center p-4">
				<h1 className="text-4xl font-bold">Welcome to EduBank</h1>
				<p className="mt-4 text-lg">Your educational banking solution.</p>
				<Link href="/uploader" className="mt-6 inline-block rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600">
					Go to Uploader
				</Link>
			</main>
		</div>
		</>
	);
}
